# Generated by Django 5.2.5 on 2025-08-26 11:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisations', '0001_initial'),
        ('transports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_to', to='localisations.localisation')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_from', to='localisations.localisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='transports.vehicletype')),
            ],
            options={
                'ordering': ['-time_start'],
                'indexes': [models.Index(fields=['time_start'], name='transports__time_st_b7c925_idx'), models.Index(fields=['time_end'], name='transports__time_en_84fbc3_idx'), models.Index(fields=['vehicle_type'], name='transports__vehicle_131df4_idx'), models.Index(fields=['owner'], name='transports__owner_i_d43c65_idx'), models.Index(fields=['origin'], name='transports__origin__83c4f1_idx'), models.Index(fields=['destination'], name='transports__destina_1d1742_idx')],
            },
        ),
    ]
