# Generated by Django 5.2.5 on 2025-09-02 20:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisations', '0001_initial'),
        ('transports', '0003_route_cancelled_at_route_sold_at_route_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(help_text='1..5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='crew',
            field=models.CharField(choices=[('single', 'Single crew'), ('double', 'Double crew')], db_index=True, default='single', max_length=10),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['crew'], name='transports__crew_acacd5_idx'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='localisations.localisation'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transports.route'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route', 'order'], name='transports__route_i_7ff802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'order')},
        ),
    ]
