# Generated by Django 5.2.5 on 2025-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_routestop_route_crew_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='pay',
            new_name='price',
        ),
        migrations.AddField(
            model_name='route',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Polish Zloty'), ('EUR', 'Euro')], db_index=True, default='EUR', max_length=3),
        ),
    ]
