# Generated by Django 5.2.5 on 2025-09-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0005_rename_pay_route_price_route_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='attribute',
            field=models.CharField(blank=True, db_index=True, help_text="Single character attribute for filtering, e.g. 'R', 'P'", max_length=1),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
