# Generated by Codex on 2026-03-15

from django.db import migrations, models


def pln_to_eur(apps, schema_editor):
    Route = apps.get_model("transports", "Route")
    Route.objects.filter(currency="PLN").update(currency="EUR")


class Migration(migrations.Migration):

    dependencies = [
        ("transports", "0008_routephoto"),
    ]

    operations = [
        migrations.RunPython(pln_to_eur, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="route",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro")],
                db_index=True,
                default="EUR",
                max_length=3,
            ),
        ),
    ]
