# Generated by Django 5.2.5 on 2025-09-07 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verified_at_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code, e.g. #RRGGBB.')]),
        ),
    ]
