# Generated by Django 5.2.7 on 2025-10-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVerificationDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Pending verification',
                'verbose_name_plural': 'Pending verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.verificationdocument',),
        ),
    ]
